version: '3.7'

services:
  currency-exchange:
    image: yichengwei/currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network:
  
