apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: in28min/mmv2-currency-conversion-service:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-currency-conversion-service
        # Use the environment variables from the ConfigMap
        envFrom:
        - configMapRef:
            name: currency-conversion-config
        # 2 probes supported by spring boot actuator
        # If the readiness probe fails, the pod will not receive traffic from the service
        readinessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        # If the liveness probe fails, the pod will be restarted
        livenessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/liveness
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: currency-conversion # Select the deployment with this label
  sessionAffinity: None
  type: LoadBalancer

---

# ConfigMap to store environment variables for currency-conversion deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: currency-conversion-config
  namespace: default
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange