version: '3.7'

services:
  currency-exchange:
    image: yichengwei/currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/ # Connect to naming server
  
  naming-server:
    image: yichengwei/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network:
  
